# LOCALE - CONFIGURACAO DE TIMEZONE
spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt_BR



# MYSQL - CONFIGURACAO DE CONEXAOCOM O BANCO DE DADOS
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/demo_park_api?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=mysql
spring.datasource.password=#SENHA_BANCO_AQUI

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update



